### ISSUE TITLE
YourClass.sploits()

### ISSUE THREAD

**Issue by dabula-s** [Graph-X/davscan#4]
In this case we can't write .sploits(), because sploits is an attribute of class not a function. As I saw in your code.
```
[*] Server uses PHP and is at version 5.6.32
Traceback (most recent call last):
  File "davscan.py", line 296, in <module>
    main()
  File "davscan.py", line 130, in main
    f = fingerprinter.fingerprint(sess,purl,msf,dos) 
  File "/wd/fingerprinter.py", line 62, in fingerprint
    x = xfind(r.headers[h], msf, dos)
  File "/wd/fingerprinter.py", line 191, in xfind
    if PHP(n[1],msf,dos).sploits() is not None:
TypeError: 'dict' object is not callable
```

**Comment by Graph-X** [comment]
I think I fixed it.  Go fetch the latest and let me know if it's still fucked up.

**Comment by Graph-X** [comment]
I'm gonna assume this is working and close the issue.  If I made an ass of you and me in assuming then we can reopen the issue and go from there.
